repository: minli-portfolio/minli-portfolio.github.io
title: Min's Portfolio
description: Data Visualization | Tableau | Design Enthusiast
remote_theme: pages-themes/minimal@v0.2.0
url: "minli-portfolio.github.io"
